name: "Pull Request Tests"

on:
  pull_request:

jobs:
  unit-test-pr:
    runs-on: ubuntu-latest
    container: python:3.9

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      
      - name: Install dependencies
        run: python -m pip install -r requirements.txt

      - name: Run tests
        run: pytest

